### PR TITLE
Add prettier npm scripts, run prettier on all files

### PR DESCRIPTION
**Pull request by cxcorp**
This PR adds the `prettier` and `prettier:check` npm scripts. The former formats all files that match the glob `./**/*.{js,jsx,ts,tsx,css,mjml}`, and the latter prints checks the formatting and prints warnings if some fail.

We use `--cache` to cache each files by content hash, so prettier doesn't need to run if the file hasn't changed. Clear the cache by running `prettier --write` without `--cache`.

Commit 890369075008e797999cbd983170c2891e7331d3 can be ignored in git-blames via https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/

### CODE REVIEW

**Comment by ConcernedHobbit** [comment]
Couldn't we add the git-blame to the entire repo? I think I recall major repositories doing something that automatically adds it on `git clone` for the entire rpeo

**Comment by ConcernedHobbit** [comment]
Seems like it's only for GitHub; https://www.stefanjudis.com/today-i-learned/how-to-exclude-commits-from-git-blame/#fun-fact%3A-github-picks-up-%60.git-blame-ignore-revs%60

"[If the file holding your ignored commits is named .git-blame-ignore-revs, GitHub picks it up automatically](https://docs.github.com/en/repositories/working-with-files/using-files/viewing-a-file#ignore-commits-in-the-blame-view)"

**Comment by cxcorp** [comment]
👍 added .git-blame-ignore-revs

**Comment by cxcorp** [comment]
Seems to work: https://github.com/TKOaly/baseball-bat/blame/72df17939b6b37bdc2e2eed0f15747aeb1be3b67/backend/api/accounting.ts

image

**Comment by ConcernedHobbit** [comment]
Also helps in setting it up locally, keeping a history of commits that should be ignored. LGTM!

**Comment by cxcorp** [comment]
We could also add a `postinstall` script that adds the revfile if it is not running in CI, but personally I usually check blames via github anyways.

**Comment by ConcernedHobbit** [comment]
Could consider adding other lint-heavy commits;
33d41b3
3ceb7b3

**Comment by cxcorp** [comment]
We could, but those commits include the config changes in eslintrc so they won't be visible then 🤔

**Comment by ConcernedHobbit** [comment]
> We could, but those commits include the config changes in eslintrc so they won't be visible then 🤔

These seem to be mainly overridden, and a small price to pay. Agree though, we can leave these out.

**Pull request merged**
